-- Reverses 0006_rls_policies.sql
drop policy if exists audit_select_own              on public.audit_log;
drop policy if exists scheduled_delete_own_business on public.scheduled_posts;
drop policy if exists scheduled_update_own_business on public.scheduled_posts;
drop policy if exists scheduled_insert_own_business on public.scheduled_posts;
drop policy if exists scheduled_select_own_business on public.scheduled_posts;
drop policy if exists posts_delete_own_business     on public.posts;
drop policy if exists posts_update_own_business     on public.posts;
drop policy if exists posts_insert_own_business     on public.posts;
drop policy if exists posts_select_own_business     on public.posts;
drop policy if exists accounts_delete_own_business  on public.social_accounts;
drop policy if exists accounts_update_own_business  on public.social_accounts;
drop policy if exists accounts_insert_own_business  on public.social_accounts;
drop policy if exists accounts_select_own_business  on public.social_accounts;
drop policy if exists members_delete_by_owner       on public.business_members;
drop policy if exists members_update_by_owner       on public.business_members;
drop policy if exists members_insert_by_owner       on public.business_members;
drop policy if exists members_select_own_business   on public.business_members;
drop policy if exists businesses_update_by_manager  on public.businesses;
drop policy if exists businesses_select_own         on public.businesses;
drop policy if exists mfa_required on public.audit_log;
drop policy if exists mfa_required on public.scheduled_posts;
drop policy if exists mfa_required on public.posts;
drop policy if exists mfa_required on public.social_accounts;
drop policy if exists mfa_required on public.business_members;
drop policy if exists mfa_required on public.businesses;
revoke all on public.audit_log       from authenticated;
revoke all on public.scheduled_posts from authenticated;
revoke all on public.posts           from authenticated;
revoke all on public.social_accounts from authenticated;
revoke all on public.business_members from authenticated;
revoke all on public.businesses      from authenticated;
